// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();

  /// {@macro assets_generator.assets_app_icon_svg.preview}
  static const String assets_app_icon_svg = 'assets/app_icon.svg';

  /// {@macro assets_generator.assets_back_arrow_png.preview}
  static const String assets_back_arrow_png = 'assets/back_arrow.png';

  /// {@macro assets_generator.assets_brain_png.preview}
  static const String assets_brain_png = 'assets/brain.png';

  /// {@macro assets_generator.assets_drop_down_icon_png.preview}
  static const String assets_drop_down_icon_png = 'assets/drop_down_icon.png';

  /// {@macro assets_generator.assets_ic_clock_png.preview}
  static const String assets_ic_clock_png = 'assets/ic_clock.png';

  /// {@macro assets_generator.assets_ic_green_tick_png.preview}
  static const String assets_ic_green_tick_png = 'assets/ic_green_tick.png';

  /// {@macro assets_generator.assets_ic_location_png.preview}
  static const String assets_ic_location_png = 'assets/ic_location.png';

  /// {@macro assets_generator.assets_img_png.preview}
  static const String assets_img_png = 'assets/img.png';

  static const String assets_models_dummy_json = 'assets/models/dummy.json';

  /// {@macro assets_generator.assets_user_placeholder_png.preview}
  static const String assets_user_placeholder_png =
      'assets/user_placeholder.png';
}
